packages:
  - packages/*
  - examples/*

catalog:
  '@storybook/addon-vitest': 10.5.0
  '@storybook/react-vite': 10.5.0
  '@types/node': 24.13.3
  '@types/pngjs': 6.0.5
  '@types/react': 19.2.17
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 6.0.3
  '@vitest/browser-playwright': 4.1.10
  cac: 7.0.0
  pixelmatch: 7.2.0
  playwright: 1.61.1
  pngjs: 7.0.0
  react: 19.2.7
  react-dom: 19.2.7
  storybook: 10.5.0
  typescript: 6.0.3
  vite: 8.1.4
  vite-plus: 0.2.4
  vitest: 4.1.10

blockExoticSubdeps: true

versioning:
  changelog:
    storage: repository

allowBuilds:
  esbuild: false

minimumReleaseAge: 4320

verifyDepsBeforeRun: install
